/**
 * 侧边栏展开策略 —— 全局生效（所有产品 / 所有版本 / 后续新增的文档）
 *
 * 需求：进入文档后，一级目录默认展开（露出二级目录）；二级及更深的目录默认收起，
 *       不往下露出文档/三级目录。所有层级都保留折叠箭头，用户可手动展开收起。
 *
 * 实现方式：不动任何 sidebars.js / versioned sidebars，而是在渲染前统一改写 category 的 collapsed
 *   collapsed —— 初始折叠状态。
 *              level === 1（一级）→ false，默认展开，露出二级目录；
 *              level >= 2（二级及更深）→ true，默认收起，不往下露出文档。
 *   collapsible 不改写（sidebars 里也没有显式声明过，默认 true），所以每层都能手动展开/收起。
 *
 * level 由 Docusaurus 自己传入：桌面端与移动端都是 <DocSidebarItems level={1}>，
 * Category 内部递归子项时传 level + 1（见
 * @docusaurus/theme-classic/src/theme/DocSidebarItem/Category/index.tsx:305）。
 * 因此这里每层只处理当前层，下钻交给组件自身的递归，层级判断天然正确。
 *
 * 为什么不在 sidebars.js 里改：本项目（含 v1 的 versioned JSON）的 category 都是显式声明的，
 * 而 sidebarItemsGenerator 只对 autogenerated 项生效、管不到手写项；逐个文件改要动 20+ 处，
 * 且以后新增分类会漏。这里一处覆盖全部。
 *
 * 上游依据（Category/index.tsx 的折叠状态初始化）：
 *   initialState: () => {
 *     if (!collapsible) return false;            // 不可折叠 → 强制展开
 *     return isActive ? false : item.collapsed;  // 当前文档所在分类永远自动展开
 *   }
 * 所以即使这里把二级设为 collapsed: true，当前阅读的文档所在的那条链路（一级 → 二级）
 * 仍会被自动展开，用户始终能看到自己在目录中的位置；同级其他二级保持收起。
 */
import React, {memo, useMemo} from 'react';
import DefaultDocSidebarItems from '@theme-original/DocSidebarItems';

function DocSidebarItems({items, level = 1, ...props}) {
  // 用 useMemo 缓存：items 引用不变时不产生新数组，下面的 memo 才能真正挡住重复渲染
  const patchedItems = useMemo(
    () =>
      items.map((item) =>
        item.type === 'category'
          ? // 一级展开露出二级；二级及更深收起，不露出文档
            {...item, collapsed: level > 1}
          : item,
      ),
    [items, level],
  );

  return (
    <DefaultDocSidebarItems items={patchedItems} level={level} {...props} />
  );
}

// 官方实现同样用 memo 包裹（注释 "Optimize sidebar at each level"），保持一致
export default memo(DocSidebarItems);
